version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
